### ISSUE TITLE
Setting options for pngquant

### ISSUE THREAD

**Issue by hernandezharries08** [kornelski/pngquant#287]
I'm just wondering what's wrong with this code? I'm trying to set the quality for the pngquant optimizer and I'm setting it like this

$factory = new \ImageOptimizer\OptimizerFactory(array(
        'ignore_errors' => false,
        'pngquant_options' => array('--force','--quality=65-80')
    ));

I know my syntax might be wrong so any help would really be appreciated.

It works if I remove the '--quality=65-80' part

**Comment by ericcobia** [comment]
I have the same issue. when i select ANY quality option, --quality=0-45, 60-80, anything i get grayscale images instead of palette/ index color

it works correctly without a quality specified

**Comment by kornelski** [comment]
Make sure you have pngquant 2. 

Some outdated Linux distributions still have pngquant from late '90s, which doesn't support the quality option, and has very low quality output.

**Comment by ericcobia** [comment]
Hello
i have the most current version 2.11
yesterday i recompiled with libpng 1.6.27 
before it was 1.2.54 since I'm on ubuntu 16.04

even with the recompile, oddly i get lots of these too so i wonder if its something else
*** Error in `/usr/local/bin/pngquant': malloc(): memory corruption:


my code is:
				if (true) {
				//$pngquant_source = escapeshellarg($chosenVariationFile);
				//$pngquant_destination = escapeshellarg(CTD_BASE_PATH.'/clipart/'.$fileNameOnly.'.png');							
				
				$iM = "/usr/local/bin/pngquant"." ".
				" ". //defineing colors - can be blank?
				
				"--force ". //force file OVERWRITE
			//	"--ext .png ". //save to same file name // comment this out for the item below -- output 
		//		"--quality 60-80 ". //quality range - enabling this causes grayscale images instead of index pallette ones
				"--speed 8 ". //speed default is 3,  11 is super fast, 10 is 8x faster than deafult of 3
				"--nofs ". // disable dithering - maybe faster
				"--output ". escapeshellarg($new_source_full)." ". //must be before input, save to same file name 
				escapeshellarg($new_source_full)." "; ///input file goes last
				
				$exec_return = exec($iM);
				}	


Thank You!


--
Eric Hilferding
President
ClassB.com <http://classb.com/>
9437 Corporate Lake Drive
Tampa, FL 33634

1-800-851-4020
My direct extension is 101
eric@classb.com <mailto:eric@classb.com>

ClassB® now offers Embroidered patches! Custom Embroidered Patches from ClassB <http://www.classb.com/patches/>

If I can be of any assistance, please call or email me.

**Comment by kornelski** [comment]
> Error in `/usr/local/bin/pngquant': malloc(): memory corruption:

Is there more information printed about this error? That doesn't seem enough to figure out what's happening.

Can you recompile it with debug assertions and see if it catches anything? (`./configure --enable-debug`)

If debug assertions don't catch, can you run it under lldb/gdb or valgrind?
