### ISSUE TITLE
Please add option to respect transparent pixel rgb values

### ISSUE THREAD

**Issue by powof2** [kornelski/pngquant#298]
Hi,
thank you for this great tool.

When image used as texture in game, renderer will use texture filtering to smoothly render the texture: it will sample from neighboring pixels to render the final image. if neighboring transparent pixels rgb values are significantly different from current solid pixel, color will bleed. to prevent this from happening, artist often add padding edges to the solid color area, padding colors are same RGB values with target solid area but their alpha are 0 (totally transparent).

Same filtering artifacts happens to 2d image as well when they are get scaled down (zooming out).

but it looks pngquant will drop all the transparent color rgb values to set them to same transparent color to reduce final image size, this sometimes is unwanted behaviour (to me, its always unwanted, because i'd like to add transparent padding colors to every png i'm working on to make them looks great) , so can you please consider to add option to reserve transparent pixel rgb values? 

thank you.

**Comment by kornelski** [comment]
The bleeding is a problem because rendering is not done in premultiplied alpha space: http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/

This is essential a bug/bad design to use straight alpha instead of premultiplied.

pngquant uses premultiplied alpha exclusively, which means:

* it does handle blending of transparent colors well
* it's technically incapable of preserving RGB of alpha=0 colors

So the change you request would be technically very difficult, and seriously harm compression and quality of the output (since previous palette colors would have to be spent on the invisible RGB values).

I suggest:

1. Fix/configure your engine to use premultiplied alpha
2. If you can't, then add a postprocessing step to images after compression, before rendering, to add the bleed pixels

**Comment by powof2** [comment]
Thanks for the reply,  kornelski.
I prefer first one (premultiplied alpha), most of the textures can be done off-line, while some can not, for example, font, user profile pictures. Considering the fact that adding padding colors wont solve the bleeding problem thoroughly, i'll try the premultiplied alpha method. thank you for the link.
