### ISSUE TITLE
Question about GPL license.

### ISSUE THREAD

**Issue by margox** [kornelski/pngquant#332]
Hi! I am developing a picture compression program that supports multiple formats, which uses `pngquant`(in fact, I am using a bin wrapper named [pngquant-bin](https://github.com/imagemin/pngquant-bin) which licensed under MIT).

I want to know if I open the source code of my app on github, then do I have the right to sell my app without buying your commercial license?

**Comment by kornelski** [comment]
I think [pngquant-bin's license information is misleading](https://github.com/imagemin/pngquant-bin/pull/105), because GPL applies to it, too.

[You have the right to sell GPL-licensed software](https://www.gnu.org/philosophy/selling.en.html), but you don't have a right to stop anyone from distributing it further (i.e. also selling your program, or giving away for free the copy they bought).

You need the commercial license if you want ability to keep your source secret and prevent others from sharing the program.

**Comment by margox** [comment]
It's a little difficult for me to buy a commercial license right now. If I use` pngquant` as an optional plug-in for my app, open the source code of the plug-in, and let the user decide whether or not to install the plug-in, will my app not be subject to the GPL? If my app can be sold later, I will be able to purchase commercial license.

**Comment by jibsen** [comment]
IANAL, but you might find the GPL FAQ useful, for instance:

https://www.gnu.org/licenses/gpl-faq.html#GPLWrapper
https://www.gnu.org/licenses/gpl-faq.html#NFUseGPLPlugins

You may need legal advice to figure out what constitutes a combined program.

**Comment by margox** [comment]
The articles you listed above helped me a lot! Thank you very much!
