### ISSUE TITLE
It’s probably buggy, when source and destination files are the same.

### ISSUE THREAD

**Issue by godskiy** [kornelski/pngquant#342]
When I use source file as an argument for output file in some cases it comes to file deletion. Any ideas?  It perfectly works, when I replace source file with output file programmatically.

**Comment by zvezdochiot** [comment]
@godskiy say> Any ideas?

Bad idea!

**Comment by kornelski** [comment]
Be careful not to use shell redirection `<` and `>`, because that will blow up, and it's shell's doing, so pngquant can't help it.

But if you use regular arguments, it can work. I just don't recommend it, because conversion is lossy, so you need to make sure you have a backup of the original file in case you don't like the converted one.

**Comment by godskiy** [comment]
Okay, after all, best choice was not to use path of destination file as an argument for output file. Seems like it may occur some collisions. So, as an example in C#, I quantized destination file, then I replaced destination file with output file via System.System.IO.File.Replace.
