### ISSUE TITLE
Green areas in alpha

### ISSUE THREAD

**Issue by ignazkevenaar** [kornelski/pngquant#353]
Hi, we use this library to compress textures for online use with Three.js. Sometimes when we use transparent textures compressed using pngquant we see some green artifacts in the 3D engine. These artifacts do not show up when using the original 24-bit PNG.

I've done some investigation and narrowed it down to a suspicious green color found in areas that are normally made transparent by the alpha layer.

This can only be seen in some image viewers, especially those that have issues viewing alpha channels. I've tested it in the Windows XP version of mspaint.

Your test image compressed with pngquant exhibits a green color:
![Example image with green alpha shown](https://i.imgur.com/3f7FzTt.png)

When using a different service, that also uses PNG compression to 8-bit with alpha channel, the green area is not there, and the image works without artifacts in our Three.js scene.

Weird thing is that this rendering issue doesn't show up in IE11, but it does in all other desktop browsers we can test on.

Is there anything that can be done about this? Thank you in advance!

**Comment by kornelski** [comment]
Yes, there is an arbitrary color set for pixels that have `alpha == 0`. This is not a bug. If this color affects your rendering, this is a bug/deficiency in your renderer: it's incorrectly using uncorrelated alpha instead of premultiplied alpha when blending colors.

You are probably relying on "bleeding" workaround in your assets, and pngquant will not preserve that workaround on purpose, because:

* pngquant operates in premultiplied alpha internally, where RGB colors of transparent pixels are equal to division by zero.

* it wastes precious palette entries on colors that cannot be seen in correct implementations.

The issue is explained here:

http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/

This is a wontfix from me. You should either switch your blending to premultiplied alpha, or add bleeding workaround as a postprocessing step *after* decoding the image, not before encoding.

**Comment by ignazkevenaar** [comment]
Thank you very much for the insight on this issue and the reading material. It helps us to understand the reason behind this problem better.
We're going to take this up with the rendering library to see if they can shine any further light on this.

**Comment by callegar** [comment]
I am observing a phenomenon that is possibly related.

I have an image with transparency. When I use pngquant on it everything is fine as long as I use a large enough number of quantization levels. Below a certain point, the part of the image meant to be transparent becomes gray when I import it in some documents. There the page background is white, so the transparent part should remain white. Even showing the image with `okular` the KDE PDF/PNG/+more viewer, the gray background is there.

Maybe, it is an issue with the renderer. Yet, I cannot change the renderer I will ultimately need to use, so this is a problem that prevents me from using the low number of quantization levels, that I would like to use.

Wouldn't it be possible to have an option with pngquant to force an rgb color to be unconditionally preserved in its output. If I understand correctly, this might help: by assuring that white is there, probably the white bits that are also white would remain white.

**Comment by kornelski** [comment]
If you specify very low number of colors for a semitransparent image and get washed out background, it's not caused by the issue reported here. It's just caused by not having enough palette entries left to keep all semitransparent levels. Allowing more colors is the right solution.

----

pngquant preserves RGB color in semitransparent pixels. 

It only can't preserve RGB values of exactly fully transparent "color" with alpha = 0. Only *one* palette entry where the alpha is *exactly* 0 gets arbitrary RGB values. 

That's because pngquant uses `r*a, g*a, b*a` in its color model. Multiplying by any other alpha value isn't a problem and is easily reversible. Multiplying by 0 is always 0, and it's irreversible.
