### ISSUE TITLE
Possibility of adding liq_image_create_argb()

### ISSUE THREAD

**Issue by Bill-Stewart-1** [kornelski/pngquant#392]
It is currently difficult to use libimagequant to work with Cairo or X buffers because they are ARGB and libimagequant only has data import for RGBA pixels.  It would be very helpful to have an import option that works on the buffers without having to rebuild them pixel by pixel first.  The export function is less of a concern because the output is typically right to a file, not back to the original buffer.

**Comment by kornelski** [comment]
I suggest using byte-swapping callback for this:

https://pngquant.org/lib/#liq_image_create_custom

Any function I can add is going to do precisely this, or copy and swap pixels, because the rest of the codebases uses rgba and I'd have to make a big code-size doubling copy'n'paste to make argb-native version.
